title: Practice MK_Just_the_Docs
description: Ćwiczonka fajne słodkie przyjemne
theme: just-the-docs

url: https://Lipkowski.github.io/Practice_MK

aux_links:
  Template Repository: https://github.com/Lipkowski/Practice_MK
  
color_scheme: dark

heading_anchors: true
